### ISSUE TITLE
Benchmark performance

### ISSUE THREAD

**Issue by mitchtbaum** [iwillspeak/ullage#20]
Fibonacci looks like the best practice for this, going by these resources:

- https://github.com/drujensen/fib
- https://news.ycombinator.com/item?id=5204426
- https://news.ycombinator.com/item?id=18091655

With just one machine's benchmark of Ullage and another language or two, we could get a good sense of its general speed.

**Comment by iwillspeak** [comment]
Nice. I’ll have a look at putting some benchmarks up. Maybe a script which other can run too.
