### ISSUE TITLE
I got a name for ya, Will..

### ISSUE THREAD

**Issue by mitchtbaum** [iwillspeak/ullage#27]
How do you like,
**`speakeasy`**
?

**Comment by iwillspeak** [comment]
Lol. It is amusing but:

 1. I’d rather not put my own name into the language
2. I’d kind of settled on the name Natterjack. This is the continuation of my previous language experimentation under that name.

**Comment by iwillspeak** [comment]
This name is really growing on me though. Think I might have to use it for some part of this language.
