### ISSUE TITLE
new language worth checking out

### ISSUE THREAD

**Issue by naturallymitchell** [iwillspeak/ullage#28]
[JazzScript](https://github.com/jazz-lang/JazzScript)

how does it look to you, Will?

**Comment by iwillspeak** [comment]
Looks interesting. Quite JS like. That could be a good thing if some of the wierd bits of JavaScript haven't been copied. Looks like quite a minimal and well-organised compiler too. Probably lots in there to learn from. The really interesting bit seems to be that `gc-rs` directory. Pretty nice way of doing garbage collection.
